import type { Metadata } from "next";
import "@/app/globals.css";
import Navigation from "@/components/navigation/navigation";
import Footer from "@/components/navigation/footer";
import { Geist, Geist_Mono } from "next/font/google";
import "leaflet/dist/leaflet.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AppointCare",
  description: "Generated by create next app",
};

export default function PatientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full">
      <Navigation />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
