import DoctorShell from "@/components/navigation/doctor_navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Doctor Page",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="">
      <DoctorShell>{children}</DoctorShell>;
    </div>
  );
}
