import DoctorShell from "@/components/navigation/doctor_navigation";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Doctor Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <DoctorShell>{children}</DoctorShell>;
}