import type { Metadata } from "next";
import "@/app/globals.css";
import Footer from "@/components/navigation/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full">
      <div className="pt-5 sm:pt-21">
        {" "}
        <main className="flex-1">{children}</main>
        <Footer />
      </div>
    </div>
  );
}
