import DoctorShell from "@/components/navigation/doctor_navigation";
import { Metadata } from "next";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { connectDB } from "@/config/mongodb";
import { Doctor } from "@/models/doctor";
import { resolveDoctorApplicationStatus } from "@/config/doctorStatus";

export const metadata: Metadata = {
  title: "Doctor Page",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Doctors whose application is pending or rejected (including doctors
  // revoked while signed in) may not use the doctor area.
  const { userId } = await auth();
  if (userId) {
    await connectDB();
    const doctor = await Doctor.findOne({ clerkId: userId, role: "doctor" })
      .select("applicationStatus verified")
      .lean();
    if (doctor) {
      const status = resolveDoctorApplicationStatus(doctor);
      if (status !== "accepted") redirect(`/account-status?status=${status}`);
    }
  }

  return <DoctorShell>{children}</DoctorShell>;
}
