import type { Metadata } from "next";
import "@/app/globals.css";
import Navigation from "@/components/navigation/navigation";
import Footer from "@/components/navigation/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full">
      <Navigation />
      <main className="pt-21">{children}</main>
      <Footer />
    </div>
  );
}
